### PR TITLE
Added more start-up strings and thanks upvote string to /r/xdacirclejerk

### PR DESCRIPTION
**Pull request by KonradIT**
Hi ccrama and the team :)

I added a couple more strings to the start up screen.

**List of what I added:**
* Finding dank memes
* Showing the rarest pepe
* Thanking Mr. Skeletal
* Avoiding the downvote brigade
* Asking for a friend
* Doing it for science
* Coming here to say this
* Getting gold from a stranger
* Showering in downvotes
* Fixing that for OP
* Making it to the frontpage

Also, as on ACJ sub the upvote text is "upDuARTe", I added the text "thanks" on XDACirclejerk sub (because on XDA there is a thanks count)

Screenshot: http://i.imgur.com/Ei7hO5V.png

---

/u/konrad-iturbe on reddit

### CODE REVIEW

**Comment by The0x539** [comment]
Stylistically it conflicts, but in a vacuum it makes more sense to be "thanking mr skeltal" than "Thanking Mr. Skeltal".

**Comment by KonradIT** [comment]
@The0x539 thanks mr dev ;)

**Comment by The0x539** [comment]
thank*

Also, I'm sadly no dev, just a guy who does everything someone like l3doom would *except* development :P

**Comment by KonradIT** [comment]
@The0x539 wat, what do you mean by except development?

**Comment by ccrama** [comment]
Awesome! Thank you very much :). As for the splash screen titles, the splash screen now only shows on first startup (as it boots too fast to show it), but it'll still use those strings (liking them!). And I'm the dev ;)

**Comment by KonradIT** [comment]
@ccrama thank mr real dev

**Comment by The0x539** [comment]
@KonradIT I lurk around on the repo, occasionally do a French localization or two, handle issues at times, and discuss development on IRC.

**Comment by KonradIT** [comment]
btw I am thinking of a feature for the app: on the comment box, add a button to show a list of copypastas, in categories (original ones / versions of Navy seals, good sh*t, walmart... / and a section to paste your own ones. Heck, maybe even a customizer copypasta tool to replace words to make custom versions of copypastas.

I will do that next week if I can, now too busy with exams and homework.

**Pull request merged**
