### PR TITLE
adds button to bottom nav bar to expand/collapse comments

### PR DESCRIPTION
**Pull request by YusefOuda**
This PR adds another icon to the bottom nav bar which when clicked, will either collapse or expand all comments.

I'm not 100% sure if the bottom nav bar is the best place for this, but I couldn't think of where else it could go.

This feature might not be a good idea at all, just thought I would throw it out there to see if it makes sense

### CODE REVIEW

**Comment by ccrama** [comment]
Thank you for the PR! What would be your use case for this button vs the button that exists in the 3 dot menu already?

**Comment by ccrama** [comment]
Ah gotcha. I wonder if it would be worth making this either a settings option, or enabled by default when you have collapsed by default set. What are your thoughts on this?

**Comment by YusefOuda** [comment]
A setting seems like a good way to incorporate this

**Comment by ccrama** [comment]
@YusefOuda there are now some conflicts due to the new settings screen, if you would like me to take a stab at it let me know!

**Comment by YusefOuda** [comment]
Sure thing, if you have time to take a look that would be great. I won't have time for a few days here.

**Comment by ccrama** [comment]
Got it implemented, thank you very much for the PR!

**Pull request merged**
