### PR TITLE
EditText highlight is now white

### LINKED ISSUE #1408: Reply input field doesn't use wubreddit's accent color and instead uses global accent
/r/grilledcheese has its accent color set to orange for me.

### PR DESCRIPTION
**Pull request by Nxt3**
It can be any color, as long as it's white ;)

Fixes #1408

### CODE REVIEW

**Comment by ccrama** [comment]
Haha, thanks

**Comment by ccrama** [comment]
This has the adverse side effect of changing all switches to white, and also you just had to put that once in the swipeable parent theme instead of every child theme. I'll look for a workaround!

**Comment by Nxt3** [comment]
Darn. :/

**Comment by Nxt3** [comment]
I know how to fix it. Will do it in the morning

**Pull request merged**
