### PR TITLE
Full-width list view mode

### PR DESCRIPTION
**Pull request by Nxt3**
- Replaces old list view style
- Thumbnails for card and middle card modes now match the style of the List mode (wider image)
- Higher resolution "NSFW" and "web" images

I gotta say, this looks much better than I had imagined. I like the card views--but I might just switch over to this on my phone.

[Looks like the last two images in this gallery](http://imgur.com/a/bNU2P). I opted for the minimal spacing as I find it better looking and less like the cards view mode.

### CODE REVIEW

**Comment by Nxt3** [comment]
Fixes #1780

**Comment by ccrama** [comment]
Looks awesome! Thank you for the PR.

One question though, does it totally replace the list view or is it an alternative to the current list view

**Comment by Nxt3** [comment]
It replaces it. Personally, I don't see the need for an option here; this looks just so much better. If you want it as an option, I can do that.

**Comment by ccrama** [comment]
Just tested it out and looks great! There is a slight padding issue with the left hand thumbnail mode, though.

And personally I don't know if it should be an option, some users like a more compact list view with smaller thumbnails vs a bigger list view, what are your thoughts on this?

**Comment by Nxt3** [comment]
I'll fix the left-hand issue, forgot to test that. 

I dunno. It's still more compact than cards; personally, I never considered using the list view mode because I found it to not look as nice as it could. [As per the post on /r/slideforreddit](https://www.reddit.com/r/slideforreddit/comments/4kfeud/what_is_everyones_thoughts_for_this_new_styling/), nobody seems to ask for it to be an option. If you like it, I say add it without an option. If enough users voice their opinion about it, I will absolutely add it as an option.

**Comment by ccrama** [comment]
Yeah you're right, adding it as an option would be a little confusing as well. If you need help with the left handed thing let me know, otherwise I'll merge when that's done. Thank you!

**Comment by Nxt3** [comment]
Fixed 👍

**Comment by ccrama** [comment]
Sweet, merging now! Thank you :D

**Pull request merged**
