### PR TITLE
[WIP] Support for Android N

### PR DESCRIPTION
**Pull request by freundTech**
Was fixed: 
- [x] App crashing on first start
- [x] App crashing when uploading images
- [x] App crashing when changing theme
- [x] Subreddit shortcuts
- [x] Completely white dialogs
- [x] Typing in drawer search field scrolls up and down
- [x] Can't leave offline mode

I only tested in the android emulator.

### CODE REVIEW

**Comment by Nxt3** [comment]
I'd add it myself (but I don't have N on my 6P yet).

Could you add `android:resizeableActivity="true"` to the AndroidManifest? This should stop the toasts saying "This app isn't supported for multiwindow" even though it works.

**Comment by ccrama** [comment]
Thank you very much for all these fixes! Do you think any of these are easy to fix? #1984

If not, that is fine. Thanks again!

**Comment by freundTech** [comment]
#1930 Still a problem
#1950 Can't reproduce.
#1951 Can't even get the long press menu to open (Not even on 6.0). Do I have to enable it in the settings?

**Comment by Alexendoo** [comment]
#1951 is from General → Subreddit search method

**Comment by freundTech** [comment]
Thanks. Also can't reproduce #1951. Popup and keyboard close correctly.

**Comment by ccrama** [comment]
You aren't going to believe this but the fix to the listview focus was this:

            drawerSubList.setFocusable(false);

**Comment by ccrama** [comment]
Fixed with a commit to master, I think the PR is ready to merge now

**Comment by freundTech** [comment]
@ccrama Not sure if this was caused by your commit (I think it was), but now as soon as you open the sidebar it scrolls down to the search instead of having you click on the search box first.

**Comment by freundTech** [comment]
Ok. Now it should be ready for merge.

**Comment by ccrama** [comment]
That is great, thank you very much!

**Pull request merged**
