### PR TITLE
Added experimental support for coloring the app icon

### PR DESCRIPTION
**Pull request by freundTech**
Inspired by Issue #242.

Probably needs more testing on different devices.

Optional improvement that could be added later: Detect if phone is rooted and offer to restart homescreen, so user doesn't have to reboot.

### CODE REVIEW

**Comment by ccrama** [comment]
Looks great, could we have an opt in in Settings > Main Theme possibly (since it's experimental)? Again, great work, thank you!

**Comment by Nxt3** [comment]
I agree. Add it to Main theme. Put a header down titled "EXPERIMENTAL". If you don't want to do that, I can after this is merged

**Comment by freundTech** [comment]
It already has a switch labelled as experimental in theme settings.
If you look at the commit and scroll all the way down you can see the label and explanation.

**Comment by ccrama** [comment]
That is awesome! Thank you

**Comment by ccrama** [comment]
It seems to remove the launcher icon on install even with the setting disabled, is there a way we could keep the "legacy" icon until the user enables the colored setting?

**Comment by freundTech** [comment]
Oh. I didn't think about that.

As far as I know there is sadly no way to prevent that. It has to do with how the custom Icon system works.
 Instead of a app Icon the app now has Activity-Alias icons. Activity-Aliases (and with them their icons) can be enabled and disabled at runtime, while app icons can only be disabled at buildtime.

The only way to implement this is to remove the app icon completely. Otherwise you will always have the app icon and an activity icon.

**Comment by Nxt3** [comment]
@freundTech This removed the debug icon for the debug builds.

**Comment by freundTech** [comment]
@Nxt3 Found the problem. It's not this PR, it's #2076 (I was sure that debug icon worked when I tested this PR).

That one fixed the icon resolutions to match googles recommendations, but didn't fix the debug icon resolutions.

The resolution mismatch made android use the original icon.
PR incoming.

**Pull request merged**
