### PR TITLE
adds comments button on vertical albums and fixes bug where the butto…

### PR DESCRIPTION
**Pull request by prashantkhurana**
…n was not visible on updating from vertical to swipe album

Screenshot 
photo_2016-07-09_02-15-43

### CODE REVIEW

**Comment by prashantkhurana** [comment]
@Nxt3 merge it 😄

**Comment by Alexendoo** [comment]
Should one of those not go in the overflow menu? Standard is 2 icons + overflow menu showing

**Comment by ccrama** [comment]
Yeah I agree, it should be an overflow action and not a top-level action

**Comment by prashantkhurana** [comment]
@ccrama @Alexendoo done.

**Comment by ccrama** [comment]
Awesome, thank you for all the PRs lately!

**Pull request merged**
