### PR TITLE
Ability to read posts later

### LINKED ISSUE #2117: Saving individual posts offline throws exception
Throws exception. Mentioned it  [here](https://github.com/ccrama/Slide/commit/17e6bd954de1aca76636f65dc04aa154330c3124#commitcomment-18888517)

Will fix it. Just wanted to create a placeholder issue so that no body else spends time on it, if they notice it.

### PR DESCRIPTION
**Pull request by prashantkhurana**
This PR finishes the read later work started by @ccrama 
	• Can store posts for reading them later.
	• These posts can be accessed both offline(cached when marked) and online
	• Can "Mark as read" the posts marked for reading later.
	• Mark as read option also in offline mode and for any offline content.
	• "Read later" is in reverse chronological order.
	• Merged read later and save offline.
	• fix  #2117 
image
image
image
image

### CODE REVIEW

**Comment by Nxt3** [comment]
"Read Later" should be below the "History" menu item.

**Comment by prashantkhurana** [comment]
@ccrama what do you say? He added that there, so I don't want to change it unless everyone agrees.

**Comment by Nxt3** [comment]
Oh you didn't add that?

**Comment by prashantkhurana** [comment]
no, some of the work was done by him. I added the offline feature to it and some other things.
Commit : https://github.com/ccrama/Slide/commit/bcef41e8ac5cc8b3c9f77dde4d28fb9766ab1a41

**Comment by ccrama** [comment]
Looks great, thank you very much for the hard work! Can't wait to release this feature :)

**Pull request merged**
