### PR TITLE
Updated translations, fixed some hard coded strings

### PR DESCRIPTION
**Pull request by Soberat**
I really hope I won't crap anything up :D

### CODE REVIEW

**Comment by Alexendoo** [comment]
Thanks for catching those ones, for the new translations though could you please submit them through https://crowdin.com/project/slide-for-reddit

**Comment by Soberat** [comment]
Will do once I get home!

**Comment by Alexendoo** [comment]
Thanks for that, from the way crowdin works it will override your changes since they're not in its own order, if you want to include translations themselves in your PR you can get the strings from https://crowdin.com/download/project/slide-for-reddit.zip, otherwise not a problem I'll do it at a later date

**Comment by Soberat** [comment]
Done. By the way, would Crowdin be able to export plurals with "many" instead of "other"? It's a minor thing but in Android Studio it reports it as an error. Not a necessity, but would be nice :)

**Comment by ccrama** [comment]
Hey just an FYI, that "donottranslate.xml" file should not be translated. Great work, though! Also feel free to join us on IRC

**Comment by ccrama** [comment]
Thank you for all the hard work!

**Pull request merged**
