### PR TITLE
Fix spacing with tables/code

### PR DESCRIPTION
**Pull request by Deadleg**
Whenever the CommentOverflow layout is used it comes with the default spacing i.e. none. This fixes it with 16px top and bottom margins + fixes the font colour.

### CODE REVIEW

**Comment by Deadleg** [comment]
Something is breaking... closing.

**Comment by Deadleg** [comment]
Not from my commits. Reopening!

**Comment by l3d00m** [comment]
Hey @Deadleg, thanks for the pr. I'll wait for @ccrama to merge it in. The failing travis is resolved with my latest commit.

One thing i noticied about tables / code blocks: If there's text below it, it looks different than the text above a code block / table. (more grey-ish and bigger). [Example post](https://www.reddit.com/r/TronScript/comments/459wpb/tron_v861_20160211_add_postrun_system_restore/) and an [image of it](https://imgur.com/chowIgF.png)

**Comment by Deadleg** [comment]
The colour is fixed, but I didn't notice the text size. Should be an easy
fix

**Comment by ccrama** [comment]
Great find! Let me know if you'd like me to merge it now or wait until the text size is fixed.

**Comment by Deadleg** [comment]
You can merge it now. I'll fix text in another pull request with some more
clean up

**Comment by ccrama** [comment]
Awesome. Thank you for the great work!

**Pull request merged**
