### PR TITLE
Added android:contentDescription strings to many image buttons.

### PR DESCRIPTION
**Pull request by nebeker**
Addresses #2983

### CODE REVIEW

**Comment by Tensounder54** [comment]
These commits are fantastic*!* When your ready for this PR to be merged let us know and we will look to merge it. Let us know if you need any help.

**Comment by nebeker** [comment]
I'm glad you think so.

I just wrote a comment on the issue thread.

I think this is ready to be merged, but I'd like some help for one aspect of this.

**Comment by ccrama** [comment]
Great work here, this is something we need to look into with future Slide development as we are really lacking on accessibility here

**Comment by nebeker** [comment]
> Great work here, this is something we need to look into with future Slide development as we are really lacking on accessibility here

Thanks, I'm glad I could help. As I mentioned [here](https://github.com/ccrama/Slide/issues/2983#issuecomment-470615423), working on this, moving forward, is fairly simple - mostly one extra line of code here and there.

I'd be glad to continue with that and do some testing along the way.

**Comment by Tensounder54** [comment]
If your willing to do that, that would be awesome!

**Pull request merged**
