### PR TITLE
Reduced number of calls to Synccit auth by 1

### PR DESCRIPTION
**Pull request by Nxt3**
Doesn't seem to break anything and I'm still able to register.

### CODE REVIEW

**Comment by ccrama** [comment]
Yeah that was most likely a bug. Thanks!

**Comment by Nxt3** [comment]
If you're talking about the bug where you have to press "Save" twice to auth with Synccit--this doesn't fix it. I was actually trying to fix that bug lol. This is just a redundant call.

**Comment by ccrama** [comment]
I was actually not aware of that. I meant that it was redundant and uneccesary was a bug

**Comment by Nxt3** [comment]
Oh. yeah; I'm actually already registered; but if I go to synccit settings and press save--it will wait for a bit then fail. If I press it again, it waits and then auths successfully.

**Comment by ccrama** [comment]
Interesting. Let me know if you find the issue!

**Pull request merged**
