### PR TITLE
share reddit shortlink when possible

### PR DESCRIPTION
**Pull request by YusefOuda**
addresses issue #2468. I tried to catch any instances where links are being shared and change it over to the shortlink. I wasn't able to test each code path since I wasn't able to pinpoint where each file was being used in the app. Any insight would be appreciated. Let me know if you see any issues

### CODE REVIEW

**Comment by YusefOuda** [comment]
@ccrama any input on this PR and also https://github.com/ccrama/Slide/pull/2485? much appreciated

**Comment by bb010g** [comment]
I don't know how I feel about this. Given the choice between sharing the permalink and a shortened URL, I'd normally go with a permalink. Could this be exposed behind a preference to use shortened by default, or some other way that provides choice when sharing?

**Comment by Nxt3** [comment]
I think, if anything, this should be a setting under "Link Handling". I personally don't care either way, but I would imagine there are people who do. Making it a toggle would be better than asking the user every single time they want to share a link.

**Comment by ccrama** [comment]
I agree with @Nxt3 on this one, shouldn't be too difficult to add a setting in for it! If you would like me to do that @YusefOuda let me know. Also sorry for being absent on Github, I have been primarily focused on Slide iOS which went into alpha testing yesterday, so things are a little busy on my end!

**Comment by YusefOuda** [comment]
I like the idea of a setting, that makes sense. I can take a stab at this tomorrow

**Comment by ccrama** [comment]
Hey just wondering what the status of this was? I can implement the setting if you'd like

**Comment by YusefOuda** [comment]
That's a good question. It's been a while, I remember being unhappy with some aspect of what I did. It's not coming back to me what that was though

**Comment by ccrama** [comment]
We were just going to make a setting for it so users can disable the shortlink if they want to. I think other than that it was working great!

**Comment by YusefOuda** [comment]
Cool, yeah if it looks good to you feel free to add the setting and we can get this merged in

**Comment by ccrama** [comment]
Decided to merge it without an option for now. If you're still interested in an option, feel free to make an issue @bb010g  and I'll take another look at it

**Pull request merged**
