### PR TITLE
Gradle cleanup

### PR DESCRIPTION
**Pull request by Jawnnypoo**
Like the title says, this tidies up the gradle files a bit. It also removes the repeated httpclient dependency to prevent build warnings. That's about it!

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Hmm, not sure why Travis failed. Anyone seen this kind of failure before?

**Comment by Alexendoo** [comment]
Restarted the build and it passed, probably just one of those oddities. Error didn't point to anything in slide anyhow

**Comment by ccrama** [comment]
Great work, thank you for the clean up!

**Comment by Jawnnypoo** [comment]
No worries, glad to help.

**Pull request merged**
