### PR TITLE
fixed sliding between comments not always loading the next page

### PR DESCRIPTION
**Pull request by kufii**
Fixes https://github.com/ccrama/Slide/issues/2192

I have very little android dev experience and I honestly have no idea if this is a good way to fix it, so feel free not to merge. It does seem to work from my testing however.

### CODE REVIEW

**Comment by kufii** [comment]
Wait. A couple bugs with this fix, give me a minute to fix them

**Comment by kufii** [comment]
ok fixed the bugs, works properly now

**Comment by ccrama** [comment]
Thank you for the PR! 

What would occur if a user opened a sub on the main screen, clicked into another sub, and then proceeded to close and try opening comments of the original sub again? Having the static instance means it would get overridden with other data, unless I'm misunderstanding the code. IIRC, this is why it creates a new instance instead of passing a static reference currently

**Comment by kufii** [comment]
Yes the second commit fixes that issue. It overwrites the static instance every time the comment screen activity is created

**Comment by ccrama** [comment]
Ah great. I'll do some testing, seems to have a merge conflict right now though! Thank you again for the PR

**Comment by ccrama** [comment]
I fixed the merge conflicts, also seems to be working. Will merge soon! Thank you!

**Comment by ccrama** [comment]
After putting this out in Alpha for a few days, this is causing quite a few crashes, specifically with these two stacktraces:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.ccrama.redditslide/me.ccrama.redditslide.Activities.CommentsScreen}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List me.ccrama.redditslide.PostLoader.getPosts()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List me.ccrama.redditslide.PostLoader.getPosts()' on a null object reference
	at me.ccrama.redditslide.Activities.CommentsScreen.onCreate(CommentsScreen.java:164)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
	... 9 more
```

and 

```
java.lang.RuntimeException: Unable to destroy activity {me.ccrama.redditslide/me.ccrama.redditslide.Activities.CommentsScreen}: java.lang.IndexOutOfBoundsException: Invalid index 18, size is 0
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5066)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5089)
	at android.app.ActivityThread.access$1700(ActivityThread.java:222)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1854)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 18, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at me.ccrama.redditslide.Fragments.CommentPage.doAdapter(CommentPage.java:1704)
	at me.ccrama.redditslide.Fragments.CommentPage.onCreateView(CommentPage.java:1018)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1277)
	at android.support.v4.app.FragmentManagerImpl.dispatchReallyStop(FragmentManager.java:2181)
	at android.support.v4.app.FragmentController.dispatchReallyStop(FragmentController.java:249)
	at android.support.v4.app.FragmentActivity.onReallyStop(FragmentActivity.java:816)
	at android.support.v4.app.FragmentActivity.doReallyStop(FragmentActivity.java:795)
	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:388)
	at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:212)
	at me.ccrama.redditslide.Activities.BaseActivity.onDestroy(BaseActivity.java:205)
	at me.ccrama.redditslide.Activities.CommentsScreen.onDestroy(CommentsScreen.java:83)
	at android.app.Activity.performDestroy(Activity.java:7102)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1170)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5044)
	... 9 more
```

I can take a look deeper into the issue soon, but probably won't happen for this update. I will revert this PR until the fixes have been made. If you would like to update the code, feel free to do so (as you know what it is doing better than I do at the moment)!

**Pull request merged**
