### PR TITLE
Support mod locking/unlocking individual comments

### PR DESCRIPTION
**Pull request by timawesomeness**

### CODE REVIEW

**Comment by Tensounder54** [comment]
Oh wait, we didn't already support this? Interesting.

**Comment by timawesomeness** [comment]
We already support locking/unlocking whole posts, just not the newer locking individual comments

**Comment by ccrama** [comment]
Just a follow up @timawesomeness did we figure out why JRAW CI was failing for this commit?

**Comment by timawesomeness** [comment]
The JRAW repository's travis config requests jdk7 which AFAIK is unavailable on travis

**Pull request merged**
