### PR TITLE
Combine OverviewBase, SubredditOverview, and SubredditOverviewSingle

### PR DESCRIPTION
**Pull request by recalculated**
Before, SubredditOverview and SubredditOverviewSingle were basically carbon copies of each other except for the layout file to be inflated. This merges them (and OverviewBase, since it only served as a parent class of the two) into one, easy to manage activity.

### CODE REVIEW

**Comment by ccrama** [comment]
Thank you very much! And oh dang, I didn't see this before I pushed my last commit. Did too much break? 

If you would like me to force merge it let me know, or if you want to try to fix the conflicts that would be awesome :)

**Comment by recalculated** [comment]
I'll go ahead and fix the conflicts, doesn't look like too much of a hassle.

**Comment by recalculated** [comment]
All good now. Just a small issue in AndroidManifest

**Comment by ccrama** [comment]
Sweet! Thank you very much

**Comment by recalculated** [comment]
No problem :)

**Pull request merged**
