### PR TITLE
advanced settings, exclude slide from opening some urls

### LINKED ISSUE #570: Change Single Mode switch description to Subreddit Tabs, and swap the behavior and default position
Such that Subreddit Tabs are on by default, instead of Single Mode being off.

### PR DESCRIPTION
**Pull request by l3d00m**
making a pr because that are a few more changes, so @ccrama should look through this

screenshot_2015-12-11-17-48-20
screenshot_2015-12-11-17-48-33

this fixes #570

### CODE REVIEW

**Comment by okungnyo** [comment]
I hate sounding like a broken record, but:

Sentence-style caps, please.

It's part of MD and more professional.

**Comment by l3d00m** [comment]
@okungnyo no problem, but what which sentence do you mean exactly?

**Comment by alexsmithfanning** [comment]
All of the words.

Default Layout > Default Layout
Base Theme > Base theme

**Comment by l3d00m** [comment]
I'm still not getting what you guys mean. @alexsmithfanning, where's the difference (for default layout)?

**Comment by ccrama** [comment]
Thank you! What settings are going under advanced?

**Comment by okungnyo** [comment]
Yeah, what @alexsmithfanning said.

**Comment by l3d00m** [comment]
@okungnyo yeah, you're right, i remember that we discussed about that in #573 and i completely forgot about that

@ccrama Cache Settings, Alternative Layout; in the general settings: animation, animation time and 'view post links in fullscreen'. @Alexendoo and @The0x539 helped me on irc with selecting the categories .

**Comment by The0x539** [comment]
"helped"

**Comment by l3d00m** [comment]
i didn't know a better word for that

**Comment by ccrama** [comment]
Ok, cool. Thank you! And ill be on more in a week or so, lots going on irl right now :(

**Comment by l3d00m** [comment]
No problem, i try to compensate your lesser activity :p

**Comment by ccrama** [comment]
:P

**Comment by okungnyo** [comment]
Oh, is that why @l3d00m has master-branch-merging rights (or whatever it's called)?

**Comment by l3d00m** [comment]
@okungnyo, yeah, that and for managing issues (closing, labels, ...). I commit smaller things directly and probably problematic / controversial things get a pr.

**Pull request merged**
