### PR TITLE
Go to comments from images

### PR DESCRIPTION
**Pull request by prashantkhurana**
This allows a user to go to comments from images/gifs/streamable/album. 

This is an alternative to #1735 
Also inspired from https://www.reddit.com/r/RelayForReddit/comments/4pxpgf/what_is_your_favourite_feature_in_relay_that/

This is most upvoted feature there. Nothing wrong with copying/taking inspiration from good features 😄  

Example: 

http://imgur.com/atVQpYa

Screenshots for streamable, album and pic
 : 
screenshot_20160706-225159
screenshot_20160706-225131
screenshot_20160706-225052

### CODE REVIEW

**Comment by ccrama** [comment]
Could you supply a screenshot of what this looks like or how it works? Thank you!

**Comment by prashantkhurana** [comment]
ohh, sorry. I didn't mean to create the PR yet. Give me 20 min. I'll upload the gifs.

**Comment by prashantkhurana** [comment]
@ccrama updated the main comment. 
Please test before merging. I have tested it all scenarios I could think of, but I could have missed some.

**Comment by ccrama** [comment]
I like it and looks good, one idea though is to make it on the left-hand side of the bar always, so it doesn't jump around with the HQ button. Great work overall though!

**Comment by prashantkhurana** [comment]
Thanks. You mean very left side , right? I'll do that.

**Comment by ccrama** [comment]
Yep, thank you!

**Comment by prashantkhurana** [comment]
How does this look? Should I move it a little to the right? or is this good?
screenshot_20160707-121213

**Comment by ccrama** [comment]
I think that looks good!

**Comment by prashantkhurana** [comment]
Done. Had to change LinearLayout to RelativeLayout to achieve it. Have a look just in case.

**Comment by ccrama** [comment]
Fixed a few small issues, otherwise I like it! Thanks

**Comment by prashantkhurana** [comment]
awesome! thanks.

**Comment by prashantkhurana** [comment]
@ccrama I noticed an issue. Due to comments being on the right, it overlays the size of the gif now. What do you think we should do?

**Comment by Nxt3** [comment]
@prashantkhurana Not sure what you mean. The gif size is displayed to the right of the comments button now.

**Comment by prashantkhurana** [comment]
ohh maybe, I did not update. Let me update.

**Comment by Nxt3** [comment]
I think ccrama fixed that.

**Comment by prashantkhurana** [comment]
ahh, awesome. Yaa, I had my version on my phone. did not checkout master.

**Comment by Nxt3** [comment]
This is missing when you view an Album in vertical mode and then tap an image.

**Comment by prashantkhurana** [comment]
I tried to do it. Turned out to be a little tricky as we are two level deep by then (have clicked the on the album and then on an image. So I left it.

**Comment by Nxt3** [comment]
You should add it to the overflow menu on the vertical album page. :D

**Comment by prashantkhurana** [comment]
yeah, that can be done, but no one would use it I am sure. It is easy to slide than to open a menu at the very top of the screen and click on a button. Lets leave it, I would say and if we get a request to add to the overflow menu, we can do that. I am expecting people to say where is it in the vertical view, but not that 'okay fine add it to the menu'  😄

**Comment by Nxt3** [comment]
All I'm saying is people who use vertical album view don't get the benefit of this. 

Also, if you start in horizontal album view, then go to vertical, then back to horizontal--the comment button is missing.

**Comment by prashantkhurana** [comment]
yes, I totally get you and I tried to add it to the individual images on the vertical album, but I couldn't. So I am all for adding it to individual images in the vertical album. But because I can't do that,  I don't think we should add it to the overflow menu to compensate for that, IMHO. But that's just me. 

> Also, if you start in horizontal album view, then go to vertical, then back to horizontal--the comment button is missing. 

Ahh, this can be fixed I think. I'll do that. thanks.

**Comment by Nxt3** [comment]
I'm not sure I see your logic. You can't have this action in one form of the album views, and not the other. It's largely inconsistent. Regardless of view, they should have the ability to do this. If you don't want to add it to the overflow menu, why not add it in the toolbar as an action in vertical album mode? That makes more sense.

**Comment by prashantkhurana** [comment]
Will add it as an item in the toolbar. That makes sense to me.

**Comment by prashantkhurana** [comment]
Although still I would doubt people would use it. It is at the very top of the screen. Nobody on a phone >=5.2 inch is going to do that. And that too is an inconsistency, why bottom everywhere but top at one place.

**Comment by Nxt3** [comment]
If that were true, why even use toolbars ;)

**Pull request merged**
