### PR TITLE
bugfix where some subs don't show up in 'go to sub'

### PR DESCRIPTION
**Pull request by prashantkhurana**
Example : Try searching for music sub in the "go to sub" .

### CODE REVIEW

**Comment by Nxt3** [comment]
Not sure I understand what this fixes. Certain subs don't show up because they aren't suggested. We have an internal list of the top (200?) subs that are suggested.

**Comment by prashantkhurana** [comment]
r/Music is one of them (500). Still doesn't show up.

**Comment by Nxt3** [comment]
oh huh. So it's because of capital letters? Makes sense.

**Comment by prashantkhurana** [comment]
Yes, exactly.

**Pull request merged**
