### PR TITLE
Use AboutLibraries to show open source attribution

### PR DESCRIPTION
**Pull request by Jawnnypoo**
This adds https://github.com/mikepenz/AboutLibraries to the project so that visitors can see the open source libraries used in the project.

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
screenshot_20161010-204701

Here is what it looks like by the way (Nexus 7)

**Comment by Nxt3** [comment]
Can you put "About Libs" in the toolbar title? This is awesome btw

**Comment by Jawnnypoo** [comment]
@Nxt3 Done!

**Comment by ccrama** [comment]
This is very cool! Thank you! I've wanted to add something similar for a long time

**Comment by Jawnnypoo** [comment]
Its awesome! I use it in a ton of my projects

**Pull request merged**
