### PR TITLE
Use regex for URL handling (fixes #619)

### LINKED ISSUE #619: Links to posts open subreddits instead of the post
Google for 'best subreddits'
->
What are the best text-based subreddits to kill time reading ...
->
https://www.google.de/url?sa=t&source=web&rct=j&url=https://m.reddit.com/r/AskReddit/comments/3pc6rf/what_are_the_best_textbased_subreddits_to_kill/&ved=0CCYQFjACahUKEwiewPnE7Z3JAhVBlQ8KHQPKCAQ&usg=AFQjCNHZj8ThwXYfzmWYQbeJ5boHeHIFJw&sig2=rP-AbnrwVf1Zq0dTPaPzEw

### PR DESCRIPTION
**Pull request by recalculated**
Before, a link to any post that contained the word 'subreddit' (i.e. https://reddit.com/r/AskReddit/comments/3pc6rf/what_are_the_best_textbased_subreddits_to_kill) would cause Slide to open the subreddit instead of the post. Now, with more precise regex handling, this is prevented.

### CODE REVIEW

**Comment by okungnyo** [comment]
Damn, you are on a roll.

**Comment by Controless** [comment]
Thanks for spending your time and making all these fixes.

**Comment by l3d00m** [comment]
Your PRs are really great!

**Comment by ccrama** [comment]
Damn dude, you're awesome! Thank you!

**Pull request merged**
