### PR TITLE
lint cleanup

### PR DESCRIPTION
**Pull request by l3d00m**
I've used lint to clean up the code. You probably should look through some of the changes because I'm a java n00b.

Another question: Is [this class](https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Visuals/RippleDraw.java) still needed? I can't find a usage and it's only causing trouble for me.

### CODE REVIEW

**Comment by ccrama** [comment]
Thanks man! I like all the changes except for the first one. I use that to keep track of my work and don't want it to go away. Could you possibly update your pull request with the titles back in it?

Thanks!

**Comment by l3d00m** [comment]
Done, but it (git commit) is a little bit odd now.

**Comment by l3d00m** [comment]
I somehow managed to split "the merge branch origin/master" in it's original commits

**Comment by ccrama** [comment]
Says there are conflicts that must be resolved. Looking into it. Maybe you're behind the main branch?

**Comment by l3d00m** [comment]
Yeah, I think I'm now behind the master. You're just too fast :p

**Comment by ccrama** [comment]
Haha no worries. Thanks!

**Comment by l3d00m** [comment]
I fucked git up a bit :p I will make a new pr later.

**Pull request closed without merging**
