### PR TITLE
Another translation fix for  "Reorder Subs" & "Reorder your subs"

### PR DESCRIPTION
**Pull request by joytrekker**
Another translation fix for  "Reorder Subs" & "Reorder your subs"

### CODE REVIEW

**Comment by l3d00m** [comment]
Hey, thanks for you help! I will upload this source file to crowdin in a few days, which will then invalidate all other translations for 'pins', so you don't have to do it for all translations

**Comment by okungnyo** [comment]
Is this because of the reorder-pins system being phased out for a more traditional reorder-subs system?

**Comment by l3d00m** [comment]
yes

**Comment by okungnyo** [comment]
What does "invalidate all other translations for 'pins'" mean?

And why will that make it so that @joytrekker doesn't "have to do it for all translations"?

**Comment by l3d00m** [comment]
it deleted all translations for the string, he doesn't have to change it manually for every language

**Comment by okungnyo** [comment]
gracias

**Pull request merged**
