### PR TITLE
Fixed NSFW videos and albums not being tagged properly

### PR DESCRIPTION
**Pull request by Nxt3**
Videos and albums weren't being tagged as NSFW

### CODE REVIEW

**Comment by ccrama** [comment]
That was on purpose, NSFW shouldn't take precedence over videos and albums

**Comment by Nxt3** [comment]
Why not? It works correctly

**Comment by ccrama** [comment]
No, it shows as NSFW Image (there is no NSFW album or NSFW video tag)

**Comment by Nxt3** [comment]
Oh. I could have sworn it showed for NSFW videos. My bad.

**Pull request closed without merging**
