### PR TITLE
more profile tabs, faster gfy loading, sorted drawer & other fixes

### PR DESCRIPTION
**Pull request by l3d00m**
- increase default notif time to 60 mins
- rename strings, delete unused & dupes
- distingush between normal user, mod, admin
- readd 'points' behind score
- remove unused imports
- catch some rare bugs (that are not fixable)
- move upvoted & saved from drawer to profile
- add disliked & hidden to profile
- unhide posts in hidden tab
- delete savedview (not needed anymore)
- remove submit from drawer (there is the fab and the sidebar)
- faster gfy loading (see #707)
- catch two rare crashes
- clear other activities in background when a new mainacitivity is laucnhed

### CODE REVIEW

**Comment by okungnyo** [comment]
"disliked " should be "downvoted", no?

**Comment by l3d00m** [comment]
@okungnyo nope, everythng alright there. the thing that get displayed is 'downvoted'

**Comment by okungnyo** [comment]
Oh, so it is "downvoted"?

**Comment by l3d00m** [comment]
Yes

**Comment by okungnyo** [comment]
Yes

**Comment by ccrama** [comment]
Dang. I love you @l3d00m

**Comment by l3d00m** [comment]
<3

**Pull request merged**
