### PR TITLE
Add option for solid image viewer background.  Delay showing progress…

### PR DESCRIPTION
**Pull request by Nath5**
… bar on image viewer for 500 ms to stop it from flashing on quickly loading images.

TODO:
I don't know where you are pulling the icons from but the new settings will need an appropriate icon.

### CODE REVIEW

**Comment by The0x539** [comment]
Hmm, this does complicate #868 slightly.

**Comment by Nath5** [comment]
I have updated the affected files using the ASOP style sheet found here:
https://github.com/android/platform_development/blob/master/ide/intellij/codestyles/AndroidStyle.xml

Please let me know if there is another style sheet I should be using.  Before I was using the default Android Studio styles.

**Comment by Deadleg** [comment]
Looks better now, thanks! I'm using the default in android studio too but I don't get that kind of formatting. Strange...

**Comment by ccrama** [comment]
Awesome! And yeah for future reference, you can click CTRL + SHIFT + L to auto-format code to Android standards using Android Studio.

Looks great, will edit the icon for you using one of the current icons in the resources directory! Thank you!

**Pull request merged**
