### PR TITLE
Update app colors to match Material Design guidelines

### PR DESCRIPTION
**Pull request by jahirfiquitiva**

### CODE REVIEW

**Comment by ccrama** [comment]
What was the reasoning to change all of the accent colors to 700?  Also mind showing some screenshots of the difference between the light and dark themes of the current version vs what you changed it to?


And if you'd like to chat, my hangouts is hapticappsdev@gmail.com, or you can join us on IRC!

**Comment by jahirfiquitiva** [comment]
@ccrama

I didn't change colors to 700. I changed them from 700 to 400 because they looked a too dark, so now they look actually accent.

Here I show you some screenshots comparison. Left is current Play Store version. Right is my build with these changes. Always.

**PRIMARY COLORS**
affix_20160922_120510

**ACCENT COLORS**
affix_20160922_120051

**LIGHT THEME - BLUE ACCENT**
affix_20160922_120123

**LIGHT THEME - TEAL ACCENT**
affix_20160922_120137

**DARK THEME - TEAL ACCENT**
affix_20160922_120149

**AMOLED WITH CONTRAST THEME - TEAL ACCENT**
affix_20160922_120205

**Comment by The0x539** [comment]
Not liking the brightening of the 'Dark' theme.

**Comment by ccrama** [comment]
I don't know, it's not bad. But the AMOLED theme for sure has to be #000000, that's the point of the AMOLED part

**Comment by The0x539** [comment]
The dark theme change just reverses #1035

**Comment by jahirfiquitiva** [comment]
@ccrama 

I didn't touch full Amoled theme. I changed Amoled Light theme, just a bit. I just darkened the cards a bit more.

@The0x539 
It just makes the dark theme follow material design guidelines properly.

**Comment by ccrama** [comment]
The AMOLED cards *have* to be #000000, that's the point of AMOLED

**Comment by jahirfiquitiva** [comment]
Better now? @ccrama

**Comment by The0x539** [comment]
@jahirfiquitiva Last time I discussed this with anyone, the dark theme, even in its darker form, still uses the set of colors from the spec, just in different places. Also worth noting that despite being cards on top of the background, the cards, with the area they take up, are essentially the actual background.

**Comment by Nxt3** [comment]
I say keep the new changes to the Dark theme. On my 6P it's practically black I can't tell a difference. I think there should be a bigger diff between Dark and AMOLED Black. Just my opinion.

**Comment by ccrama** [comment]
Would it be worth making 2 themes out of dark?

**Comment by jahirfiquitiva** [comment]
@Nxt3  yeah, that's another reason I did it,

@ccrama That's up to you.

**Comment by Nxt3** [comment]
nah. There are already so many themes. Dark should be one. The minor diff between the two dark themes just seems silly to make it's own theme. One or the other.

**Comment by The0x539** [comment]
On my OnePlus One, with an LCD panel on which AMOLED themes don't look so good, the difference is quite visible.

@ccrama Probably not, but if that did happen, it'd be best if there were the currently proposed one, 'Dark', and a "very dark", essentially inverted contrast!AMOLED

**Comment by ccrama** [comment]
Those are all valid points. Let me think about it for a little bit, and I might end up putting it into an alpha just to let it get tested out and get user feedback

**Comment by jahirfiquitiva** [comment]
@ccrama Sure, thanks for considering the changes. :)

**Comment by ccrama** [comment]
Playing around with it a bit, I do like the changes. I'll merge this and see what sort of feedback we get when I push it out to alpha. Thank you!

**Comment by jahirfiquitiva** [comment]
Thank you so much @ccrama

**Comment by ccrama** [comment]
Unfortunately the dark theme changes have received a lot of negative feedback, and I will be reverting that part of the PR. Thank you for the rest though!

**Comment by jahirfiquitiva** [comment]
@ccrama 
Ok sure. No problem. Thanks for keeping the rest. :)

**Pull request merged**
