### PR TITLE
Fixed restore backup from file

### PR DESCRIPTION
**Pull request by jseybold**
- Mimetype was incorrect, could not select .txt files
- Resolved File Not Found exception when reading/restoring backup file

### CODE REVIEW

**Comment by ccrama** [comment]
Good find, and thank you very much for the fixes! Looks like CI is failing, will take a look at that tonight

**Comment by jseybold** [comment]
Glad I could help. It was a useful feature to have so I could run a debug build with my daily configuration.

It looks like there is something wrong with the way the CI server is setup.

**Comment by ccrama** [comment]
Ah you are correct, Travis needs to be set up to accept the new API 25, @Alexendoo  is that something easy to do on your end?

**Comment by Alexendoo** [comment]
Shouldn't be too much of an issue, I'll check it out

**Pull request merged**
