### PR TITLE
Removed \n string from Album View (Imgur)

### PR DESCRIPTION
**Pull request by KonradIT**
As seen in the Imgur Album view, when there is a GIF it says TAP TO LOAD GIF, In a new line, and the \n is not parsed to make a new line.

https://imgur.com/a/F1dd9

I removed the \n ~~(sorry, no after fix screenshot because my android studio is crapping on me)~~

EDIT: updated AS to 1.5.1, here is pic: http://i.imgur.com/NWsXgbA.jpg

### CODE REVIEW

**Comment by KonradIT** [comment]
someone merge this pls

**Comment by Alexendoo** [comment]
The navigation bar shouldn't be tinted, see #618

**Comment by KonradIT** [comment]
Well, fixed! I reset --hard to the commit of removing \n

Sorry for the disturbance

**Comment by ccrama** [comment]
Good find, thanks!

**Pull request merged**
