### PR TITLE
Made long press duration longer when Peek is disabled

### PR DESCRIPTION
**Pull request by Nxt3**
- Code formatting fixes as well. Just did the following to both `onTouchEvent()`

```
if (SettingValues.peek) {
    handler.postDelayed(longClicked,
                            android.view.ViewConfiguration.getTapTimeout() + 50);
} else {
    handler.postDelayed(longClicked,
                            android.view.ViewConfiguration.getTapTimeout() + 250);
}
```

### CODE REVIEW

**Comment by ccrama** [comment]
I don't know if I agree with that fully. I like tapping for a bit longer than a tap but not quite a full long press amount

**Comment by Nxt3** [comment]
This really just reverts the old long press behavior when peek is disabled. When peek is enabled--everything you did is the same. When it's disabled, it's just how it used to be. I feel like if you have that particular thing change people are going to complain; mainly because it's too easy to trigger. I agree with you though.

**Comment by ccrama** [comment]
Ah sorry didn't fully understand it. I do agree with you on that, I forgot I turned the long presses into gesture detectors!

**Comment by Nxt3** [comment]
No worries! My bad. Super stoked for this feature. 👍

**Pull request merged**
