### PR TITLE
update strings, remove '+' from version numbers

### PR DESCRIPTION
**Pull request by l3d00m**
remove the hacking.md file

### CODE REVIEW

**Comment by ccrama** [comment]
Hey, sorry to say but this build totally broke gradle. I replaced it with the old gradle file and it still gets stuck on "Gradle: Build". Any ideas on why this might be happening?

**Comment by SolarAquarion** [comment]
Revert the commit

**Comment by ccrama** [comment]
Got it to work. Don't know what the issue was

**Comment by l3d00m** [comment]
Nice, the app is still crashing for me at every start though. (stacktrace is on irc)

**Comment by Spittie** [comment]
@l3d00m Crashes for me as too, right after the startup. Shouldn't https://github.com/l3d00m/Slide/commit/982001745143ca0285530badfcd777ce983c8420#diff-8594f6d749464cb0dabfeb55f0b75402R296 be
```java
public static ArrayList<String> modOf = new ArrayList<>();
```
? I'd guess https://github.com/l3d00m/Slide/commit/982001745143ca0285530badfcd777ce983c8420#diff-e37538ffd592870aee9fc4bfff252fbdR110 as well.

**Comment by ccrama** [comment]
Oh crap, yeah my next commit fixes that.

**Pull request merged**
