### PR TITLE
Add refresh button to action bar menu

### PR DESCRIPTION
**Pull request by recalculated**
Adds an action bar menu item to refresh instead of having to scroll all the way to the top to swipe to refresh.

### CODE REVIEW

**Comment by okungnyo** [comment]
YES!!

**Comment by ccrama** [comment]
I love you. Thank you!

**Comment by ccrama** [comment]
This seems to remove shadowbox from the menu

**Comment by ccrama** [comment]
Setting showAsAction to always fixed it, but now looks a bit jumbled. Wonder if there's a better place for Shadowbox mode or one of the other buttons...

**Comment by alexsmithfanning** [comment]
Overflow menu? Refresh should go there anyway, shouldn't it?

**Comment by ccrama** [comment]
Overflow would still add another button, still just as jumbled.

**Comment by okungnyo** [comment]
The Shadowbox mode is not really an 'action' right?

Can't it be moved to the navigation drawer, then?

**Comment by ccrama** [comment]
It's an action that only applies to the current page, just like refresh and sorting and info

**Comment by okungnyo** [comment]
What do you mean by "jumbled"? Can you show us a screenshot?

Also, side note: would you consider renaming it to [Shadowbox View]? That fits better contextually.

**Comment by ccrama** [comment]
I actually just removed the info button as it was mostly useless, looks better now :). And everything is branded with Shadowbox Mode right now, would take some work to change all of it

**Comment by okungnyo** [comment]
That's too bad, 'Mode' implies that it's a transformation of the entire app, while 'View' only the current page, like you described.

**Comment by ccrama** [comment]
Well it does open a new activity and transforms the current dataset, so mode seems more appropriate

**Comment by alexsmithfanning** [comment]
Put refresh and filter into the overflow menu. Now there's only two buttons. No jumble.

**Comment by ccrama** [comment]
3 buttons is fine, removing Info worked (no need to over complicate it with an overflow)

**Comment by recalculated** [comment]
Can you upload a screenshot? When I'm on the frontpage, refresh, sort, and shadowbox are all showing, and when I swipe to a subreddit, info and shadowbox are moved into an overflow menu

**Comment by ccrama** [comment]
Frontpage automatically hides info, which means the rest of the menu items expand out. If you have a different sub set as default, it won't look right

**Comment by recalculated** [comment]
Was commit 6d9055d meant to remove the info button?

**Comment by ccrama** [comment]
Yes, just realized that I messed up haha. Will fix in an commit later tonight!

**Comment by recalculated** [comment]
Ah, ok.

**Comment by theRealPadster** [comment]
This hasn't been added yet has it? I was thinking it would be a good idea and was going to suggest it when I found this.

**Comment by Alexendoo** [comment]
It has been added, however the change may not have hit the play store version yet

**Comment by theRealPadster** [comment]
Okay, cool. Thanks.

**Pull request merged**
