### PR TITLE
Added always show FAB in Settings-General

### PR DESCRIPTION
**Pull request by darshan099**
Fixes issue #3191 : Added a toggle to always show or hide floating action button in Settings->General

### CODE REVIEW

**Comment by ccrama** [comment]
Good stuff, thank you for the PR! I might be changing the behavior to ignore the case where the setting is enabled, as it would be calling .show() on a view that is already shown

**Comment by darshan099** [comment]
Yeah changing the behaviour to ignore that case seems correct. Thank you for merging my PR ( it was also my first PR! ).

**Comment by ccrama** [comment]
Thank you for the PR! The update with your new option is live now :)

**Comment by darshan099** [comment]
Thank you so much!

**Pull request merged**
