### PR TITLE
Change strings from reorder pins to reorder subs

### PR DESCRIPTION
**Pull request by 530farm**

### CODE REVIEW

**Comment by ccrama** [comment]
Awesome! Thank you very much

**Comment by l3d00m** [comment]
That are a lot commits :p it's possible to avoid the merge commits next time by using 'git fetch ccrama' and then 'git rebase ccrama/master' instead of 'git pull' / 'git merge ccrama/master'.

**Comment by okungnyo** [comment]
@l3d00m 

Just curious, but what did 530farm do wrong?

**Comment by l3d00m** [comment]
he did nothing wrong really, i didn't want to sound like that. It's just the commits that looks ugly

**Comment by okungnyo** [comment]
Yeah, but I'm curious. In what ways were the commits 'ugly', and what does your method (using 'git fetch ccrama' and then 'git rebase ccrama/master) do differently?

**Comment by l3d00m** [comment]
it doesn't display the 'merge remote tracking branch' commits, because they don't mean anything besides the fact that he brought his fork on this reporsitories state

**Comment by okungnyo** [comment]
danke

**Comment by l3d00m** [comment]
bitte

**Pull request merged**
