### PR TITLE
Use localized comment count

### PR DESCRIPTION
**Pull request by csdodd**
I would like to do this for subscriber count as well but it is more difficult due to it using `String.format` with this string: `%1$d subscribers` and I don't think Android will be happy casting a String to an int. I am uncertain how easy is is to change the String due to the outsourced translation system in place. I also forgot to add `getLocalizedScore` to JRAW. Will do that now.

device-2016-05-26-103145

Partial fix for #1771

### CODE REVIEW

**Comment by Alexendoo** [comment]
Users have the ability to override the locale in Slide to en_US, I believe this wouldn't accommodate that, would be perhaps better to leave the string alone in JRAW and just format it in Slide

**Comment by ccrama** [comment]
That is a good point @Alexendoo, @csdodd we might want to look into that. Your JRAW solution works well for almost every case, but if the user is in Europe and changes it to force to English, it would still show a period instead of a comma

**Comment by csdodd** [comment]
I tried it out, starting the app in a locale that uses space for divider then forcing en_US works as expected: 
no_to_en

However, after disabling en_US the number does not reset until the app is restarted - so there is a bug going the other way.

**Comment by miladmaz12** [comment]
Hey can we do this but with a user's profile link/comment karma as well?

**Pull request closed without merging**
