### PR TITLE
Implement long click on links within comments for additional actions

### LINKED ISSUE #773: Allow long click on links within comments for additional actions
When you long click a link within a comment you should have the ability to interact with the link:
 
1. see the url
2. open it in your external browser
3. share it
4. copy it to your clipboard

### PR DESCRIPTION
**Pull request by trevorhalvorson**
Fix #773
Implements long click on links within comments and provides options for opening the link externally, sharing the link, and copying the link address.

See it in action: https://youtu.be/o4lsB982L4E

### CODE REVIEW

**Comment by l3d00m** [comment]
Hey, thank you very much! The bottom sheet is a really good idea.

**Comment by okungnyo** [comment]
This is amazing.

Would it be possible to for the full URL to be shown with scrolling text?

Currently, as in the video, if the URL is too long to be displayed all at once, it shows a "..." at the end.

But what if the user wants to see the full URL without having to open it?

It would be cool if the 'bottom sheet' was open for 2+ seconds, then it would scroll horizontally and showed the full URL.

**Comment by ccrama** [comment]
Wow, this is really great work, thank you! I was trying to figure out how to code something similar, really interesting method

**Comment by trevorhalvorson** [comment]
Thanks everyone! I love Slide and hope to keep contributing.

@okungnyo that's a good idea. I'll look at it tonight, but if anyone has any ideas on how to implement this please share

**Comment by ccrama** [comment]
I don't think it's actually that important, might be too much work than it's worth @trevorhalvorson  @okungnyo 

And if you ever want to chat with me and the other contributors, we usually hang out on #slide on irc.snoonet.org :)

**Comment by l3d00m** [comment]
I would love to see you as a contributor in the future because this commit was really well thought out.   
Seeing the first part of the url is enough for me, too.

**Comment by okungnyo** [comment]
Another idea shot down.

Yay I guess!!

**Pull request merged**
