### PR TITLE
More string and layout fixes

### PR DESCRIPTION
**Pull request by Soberat**
Also, I'd rather wait for Travis this time :P Includes some other stuff while I was working on it.

### CODE REVIEW

**Comment by ccrama** [comment]
You're the best, thank you very much! This is quite a lot fixed

And yep, I'll wait this time haha

**Comment by ccrama** [comment]
Sweet, passed! Thanks again

**Comment by l3d00m** [comment]
@Soberat I've uploaded the strings to crowdin, including your translations to Polish.

**Comment by ccrama** [comment]
Thank you!

**Pull request merged**
