### PR TITLE
Redesigned sidebar with flat buttons

### PR DESCRIPTION
**Pull request by Nxt3**
Addresses #1339 

[Screenshot here](https://www.dropbox.com/s/dx6loke57323ej9/Screenshot_20160408-145130.png?dl=0)

### CODE REVIEW

**Comment by ccrama** [comment]
Yeah I like that :). Thanks!

**Comment by Nxt3** [comment]
Damn you're fast lol

**Comment by ccrama** [comment]
We're on IRC ;)

**Comment by Controless** [comment]
I like it, but I don't think the moderators icon should be a thumbs up. I preferred the old icon.

**Comment by Nxt3** [comment]
@Controless I agree. Lemme fix.

**Comment by Controless** [comment]
@Nxt3 Great! :)

**Pull request merged**
