### PR TITLE
Enhanced text display and performance

### PR DESCRIPTION
**Pull request by Deadleg**
This is far from finished so do no merge yet.

I've broken a fair amount of stuff and I need help in getting it all fixed to how it was. I think most of the work will be refactoring the views, and fix possible issues where MakeTextviewClickable was used. Maybe it would be good if this were merged into a separate branch?

This started off as a pull request to display tables, but this has since turned into much more of a refactor due to performance issues.

It looks like the scrolling performance of every list view can be fixed to reducing the nested Linear/Relative layouts in the xml. The diff in comment.xml is an example of this flattening, and it's really been the biggest factor in speeding up scrolling.

MakeTextviewClickable has also been removed, since a new instance is created on every onBindViewHolder call which is really unnecessary and had some funny logic. In doing so I've ripped out and bunch of code of with the old references and replaced it with new code that may or may not work. The most complete example is in CommentAdapter.setViews.

Current features are
* horizontal scrolling code blocks
* tables
* increased comment scrolling performance

I aim to solve the following (at least) with this pull:
* #934 done
* #440 not started
* #682 not started
* comment scrolling performance
* subreddit scrolling performance

### CODE REVIEW

**Comment by alexsmithfanning** [comment]
Holy crap! This is awesome!

**Comment by ccrama** [comment]
Awesome! I can't wait

**Comment by l3d00m** [comment]
This looks great, I'm looking forward to it! Thank you very much for that.

**Comment by ccrama** [comment]
Testing it out right now and I can't believe how smooth it all is! Can't wait to see more. 

I merged new_offline_model into Master today, so feel free to build it back off of Master. I checked and there aren't really any conflicts.

Thank you very much for this!

**Comment by ccrama** [comment]
Just making sure you got my last comment. I've closed new_offline_model, so it would be great if you could move it to Master so I can delete the branch! Also feel free to come onto IRC if you have the time :)

**Comment by Deadleg** [comment]
Moving to master.

Getting pretty close to being ready...

**Pull request closed without merging**
