### PR TITLE
v.redd.it and youtube filter fixes

### LINKED ISSUE #3384: Subreddit Content Filters do not Filter v.redd.it and Custom Domain Links
Slide version: 6.7
Android version: 11

Issue has occurred in the past (see #2783), but it seems to have resurfaced. If all subreddit content filters are enabled, posts linking directly to any v.redd.it links or links for any custom domains set to open externally still appear despite the filters.

### PR DESCRIPTION
**Pull request by MetalNeo**
Subreddit content filters will now properly filter v.redd.it and youtube.com links. Previously, both were being displayed regardless of which content filters were chosen.

Fixes #3384

### CODE REVIEW

**Comment by TacoTheDank** [comment]
Thank you! :)

**Comment by MetalNeo** [comment]
Is there anything else I need to do before this patch is applied? I've been patiently waiting for this filter fix to get merged.

**Comment by TacoTheDank** [comment]
@ccrama is the one who does the PR merging, sorry

**Comment by TacoTheDank** [comment]
Idk if ccrama will get to this, so I'll merge it.

**Pull request merged**
