### PR TITLE
Add gradle plugin for checking dependency versions

### PR DESCRIPTION
**Pull request by Jawnnypoo**
Title says it all!

`./gradlew dependencyUpdates`

### CODE REVIEW

**Comment by Alexendoo** [comment]
Android studio checks for updates and highlights those needing it for most of the repos, does this work for new versions of jitpack dependencies also? I believe that's the only one it can't reasonably cover

**Comment by Jawnnypoo** [comment]
Android Studio actually does it for very few libraries (mostly just the support libraries, Google Play Services, and some Google libraries such as GSON, in my experience). Yes, it works for jitpack so long as the dependency has been fetched by at least one person since being tagged in GitHub

**Comment by ccrama** [comment]
That is a really cool plugin, thank you for implementing it!

**Comment by Jawnnypoo** [comment]
Ahh yes, makes sense since the other PRs were accepted. I'll get that fixed later today!

**Comment by ccrama** [comment]
No worries, thank you!

**Pull request closed without merging**
