### PR TITLE
IDEA auto indent/reformat, optimize imports

### PR DESCRIPTION
**Pull request by rosenpin**
IDEA auto indent/reformat only.

### CODE REVIEW

**Comment by rosenpin** [comment]
Doesn't fit current code any longer

**Comment by l3d00m** [comment]
it should be possible to use 'git checkout idea-auto-indent' then 'git fetch ccrama' and then 'git rebase ccrama/master' to bring it up to the this repositoriy's state.

**Comment by rosenpin** [comment]
Thanks.
Will do next time, I already closed this one and opened a new PR anyway.

**Comment by l3d00m** [comment]
No problem, git is really hard for beginners.

**Pull request closed without merging**
