### PR TITLE
String externalization

### PR DESCRIPTION
**Pull request by l3d00m**
this should externalize most of the strings into strings.xml  
the newest strings aren't included though and you have to manually merge this because there are you are to fast for me :p

### CODE REVIEW

**Comment by ccrama** [comment]
Holy crap, thank you! That was a lot of work and will make localization much better in the long run! 

Seems to be an issue with the branch, though. Is it behind perhaps?

**Comment by l3d00m** [comment]
Yeah that was much work. It is behind, but I've tried to merge ccrama/master and I that was too much more work for me. Can you do it for me?

**Comment by Alexendoo** [comment]
I have merged it in https://github.com/Alexendoo/Slide, however I do not currently have the capacity to test if these changes have broken anything

**Comment by ccrama** [comment]
Yeah I can test the integrity of the merge.

**Comment by l3d00m** [comment]
[Crowdin](https://crowdin.com/page/open-source-project-setup-request) is btw a very nice site to host the translations and let them translate by the community. It's free for open source apps.

**Comment by ccrama** [comment]
Wow that is pretty awesome! Going to do that right now :)

**Comment by ccrama** [comment]
Thank you for all the hard work!

**Comment by l3d00m** [comment]
No problem, I love the idea of open-source and i'm trying to support it where i can.

**Comment by l3d00m** [comment]
Let me know if you set it up, I can help with the german translation

**Comment by ccrama** [comment]
Sweet! I will be making that account today. Thank you!

**Comment by l3d00m** [comment]
There are a few strings which are not translateable (especially the example strings), i'll make a pr tomorrow that puts them in a seperate strings file so that they aren't uploaded to crowdin

**Comment by ccrama** [comment]
Ah, yeah just realized that. Thank you!

**Comment by ccrama** [comment]
In 3 hours, Dutch, Spanish, German, and British English are all done! Thank you so much for finding that website :D

**Comment by l3d00m** [comment]
That's very nice. No problem, I've found it through another open source app.

**Pull request merged**
