### PR TITLE
Do not show "Best" option in default settings

### PR DESCRIPTION
**Pull request by christarazi**
I realized after pushing #2866 that the default settings under general incorrectly display "Best" as an option (since it is only valid for the frontpage). This fixes that.

### CODE REVIEW

**Comment by christarazi** [comment]
@ccrama Have you had a chance to take a look at these changes?

**Comment by timawesomeness** [comment]
It also shouldn't be shown when a subreddit is opened as an overlay, and on profiles

**Comment by Alexendoo** [comment]
It seems like removing it from where it _shouldn't_ be seems a little error prone&mdash;is there a way instead to only explicitly add it to frontpage?

**Comment by Alexendoo** [comment]
That sounds like a good plan. I think that would allow fixing the other thing I noticed too, that best was getting added to the bottom of the list whereas on reddit desktop it's the top entry

**Comment by ccrama** [comment]
I might be missing something but best sorting works on all subreddits for me? Works on desktop as well

**Comment by timawesomeness** [comment]
It's only a post sort on the home page. Subs just have hot. It's different from the comment sort.

**Comment by ccrama** [comment]
Hmm I don’t think that’s true. On the reddit redesign you can set sorting to hot on any subreddit. Is there any official word on how that works?

**Comment by ccrama** [comment]
* best. Sorry, replying from email

**Comment by timawesomeness** [comment]
You're not the first person I've seen say that, but it's not that way for me, I only see hot in subreddits.

Regardless i'm pretty sure it's lying and still sorting by hot because best doesn't make any sense as anything other than a home page sort, because it's built around personalizing the home page by prioritizing posts from subs you interact.

**Comment by ccrama** [comment]
@christarazi It appears that an old commit removed best from sorting in the MainActivity, and I have just removed it from the SingleSubreddit view as well. Merging now, thank you for the PR!

**Pull request merged**
