### PR TITLE
Setting for right-handed comment menu

### PR DESCRIPTION
**Pull request by Nxt3**
Mirrors the comment menu--putting the vote buttons towards the right side of the device.

#1395

### CODE REVIEW

**Comment by ccrama** [comment]
Sounds good! Also looking into making a full left-handed mode, but that's more far off :P

**Comment by Nxt3** [comment]
Shouldn't be too hard. Wish you could just "flip" everything programmatically. Essentially forcing LTR layout. I would be surprised if there wasn't a way to do that.

**Comment by ccrama** [comment]
If you set start and end values instead of right and left (ex, paddingStart instead of paddingLeft), you can do it through config changes AFAIK! Would be a lot of converting, though...

**Comment by Nxt3** [comment]
I actually had it on my todo list to accomplish that. I can start on it in the next few days. :)

**Comment by ccrama** [comment]
Awesome, thank you very much!

**Pull request merged**
