### PR TITLE
Switched gilded icon to use a bitmap instead of unicode emoji

### PR DESCRIPTION
**Pull request by freundTech**
Icon needs discussion:

### CODE REVIEW

**Comment by Nxt3** [comment]
Needs to be white since it will show up on a yellow background.

**Comment by freundTech** [comment]
With yellow background do you mean the RoundedBackgroundSpan that was over the star emoji?

I completely removed that span and instead put the imagespan there. This is how it looks now: http://i.imgur.com/JHUd2wT.png  
(I will delete the phone once this PR is merged or closed. I couldn't be leaking content from /r/lounge ;) )

**Comment by Nxt3** [comment]
Dang that looks really nice. but I think you're going to have difficulty with it showing on yellow backgrounds. For example, go color a sub yellow and see how it displays if you have "Color Card Everywhere" enabled. Not sure how you want to handle that.

**Comment by freundTech** [comment]
How about adding a small white border?
Still looks good on grey background: http://i.imgur.com/ZXz00SJ.png
And is visible on gold/yellow background: http://i.imgur.com/QRnl739.png
(Maybe a bit bigger border?)

**Comment by l3d00m** [comment]
I think the approach without border looks a little bit cleaner. You could still see a star on a hold background. I don't think that wouldn't be too big of a issue as the yellow background is probably pretty rare.

**Comment by Nxt3** [comment]
Yeah, without the border looks fine. and you can still see the number of times gilded? (If you need an example, go to /r/all and sort by Top > All Time).

**Comment by Nxt3** [comment]
Actually, try it again with a larger boarder. While you could still see the start--you won't see the outline; it should look consistent across all colors--so having it appear differently on yellow doesn't seem like the way to go imo.

**Comment by freundTech** [comment]
Bigger border grey background (with count): http://i.imgur.com/HjmSUlj.jpg
Bigger border yellow background: http://i.imgur.com/dGEPZFW.png

**Comment by Nxt3** [comment]
Do a slightly bigger border and this looks great. The smaller the border, the worse it will look on lower-res devices.

**Comment by l3d00m** [comment]
I'm still on the borderless side, even a bigger border looks not as good as no border imho.

**Comment by Nxt3** [comment]
I think it looks better without a border--but to say Yellow is "rare" shouldn't be assumed. Keeping it looking visually identical among all colors should be the goal--as that's how it was done before this PR.

**Comment by freundTech** [comment]
While I agree that it's better if it looks the same on all colors that's not at all how it was done before this PR.

Before thos PR it was a white emoji start with a md_orange_500 RoundedBackgroundSpan.

If you have a sub with color md_orange_500 you would also see just the start.

**Comment by Nxt3** [comment]
Oh duh, you're right. In that case, it should be a chance to improve upon that. However, if the general consensus is that it shouldn't have a border--then so be it. Not my choice to make; it's up to @ccrama.

**Comment by l3d00m** [comment]
@freundTech is correct [here](https://goo.gl/photos/qUoEA9ixMYYvJ2pE7) is an example. It's better to make it look differently for some users than to make it (at least in my opionion) bader looking for all users.

**Comment by Alexendoo** [comment]
rel: #1832

**Comment by ccrama** [comment]
I like it, merging now! Thank you for the hard work :)

**Comment by Nxt3** [comment]
@freundTech The gilded icon isn't centered with the comment info span https://imgur.com/tcpdrCT

**Pull request merged**
