### PR TITLE
Remove redundant encapsulating layout

### PR DESCRIPTION
**Pull request by veyndan**
I noticed that there were a lot of redundant view groups encapsulating other views, so I removed them.

### CODE REVIEW

**Comment by ccrama** [comment]
Awesome work, really cleans up a lot! I'll check this out after class and merge it asap :)

**Comment by ccrama** [comment]
Would it be possible to undo all the Settings cleanup? Those files were redundant on purpose, so you could click anywhere in the view to toggle and not just on the checkbox. Thank you!

**Comment by Nxt3** [comment]
FYI, this causes a crash when swiping back while viewing a post.

```
05-10 13:12:40.860 14339 14339 E AndroidRuntime: java.lang.ClassCastException: android.support.v4.view.ViewPager$LayoutParams cannot be cast to android.widget.RelativeLayout$LayoutParams
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at me.ccrama.redditslide.Fragments.BlankFragment.doOffset(BlankFragment.java:24)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at me.ccrama.redditslide.Activities.CommentsScreen$1.onPageScrolled(CommentsScreen.java:193)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1845)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1819)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1757)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.support.v4.view.ViewPager.performDrag(ViewPager.java:2263)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2021)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9520)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6006)
05-10 13:12:40.860 14339 14339 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable
05-10 13:12:40.862   935  6372 W ActivityManager:   Force finishing activity me.ccrama.redditslide/.Activities.CommentsScreen

```

**Comment by ccrama** [comment]
Yeah, still needs some more testing

**Comment by ccrama** [comment]
Did some testing and some tweaks, great PR! Thank you!

**Pull request merged**
