### PR TITLE
Material Redesign of slide site and more developed site (advertises features, etc)

### PR DESCRIPTION
**Pull request by richiksc**
Check it live at https://richiksc.github.io/Slide/.

This redesigns the site to Material Design using Material Design Lite from Google and is a more proper site with an app download link for Google Play, advertises the app's features, and has a link to /r/slideforreddit.

### CODE REVIEW

**Comment by The0x539** [comment]
Screenshot of bug
This happens in Firefox 54 and 57 on Win10.

Also, the screenshots should *really* show more than just changing the colors

**Comment by richiksc** [comment]
Intentional. What else should the screenshots show? This section is dedicated to customization.

**Comment by richiksc** [comment]
Tested on Chrome 60 Win10 and Chrome 60 Android 7.1.2

**Comment by The0x539** [comment]
Base themes and post layouts, some of the screenshots not having subreddit tabs.

**Comment by richiksc** [comment]
Ok. Will do tomorrow CT

**Comment by The0x539** [comment]
That scrollbar setup thing really doesn't make sense or look good if it's intentional.

**Comment by richiksc** [comment]
Temporary closing while working on changes

**Comment by richiksc** [comment]
I can't open the pull request anymore because I've emptied gh-pages, created a new branch called site and put the built version of the site in the gh-pages branch using subtree

**Comment by richiksc** [comment]
@The0x539 I've updated the setup for the screenshots. You can check it live again at the same url: https://richiksc.github.io/Slide/

**Comment by The0x539** [comment]
I could swear I'm seeing some screenshots twice :P

I suggest having six screenshots total. Three (at random) with subreddit tabs, three without. Each one with a different post layout combination. Card, list, desktop compact. Big pic, thumbnail. Actionbar, no actionbar. Selftext previews. For each of the six, different main/accent color.

**Comment by richiksc** [comment]
If you had every combination of each of the options, you would have 24
screenshots.

**Pull request closed without merging**
