### PR TITLE
Flatten a bunch of views

### PR DESCRIPTION
**Pull request by aaronpoweruser**
Clean up some unneeded views
Signed-off-by: aaronpoweuser <atlrudeboi1@gmail.com>

### CODE REVIEW

**Comment by aaronpoweruser** [comment]
Ignore this for now, I shoudl use compoundViews for the sub-reddit list.

**Comment by l3d00m** [comment]
Cleaner code is always good, thank you too for this pr!

**Comment by ccrama** [comment]
Awesome! Thank you for all the commits!

**Comment by aaronpoweruser** [comment]
I have another one coming, just need to test it some more.

**Pull request merged**
