### PR TITLE
Rename packages to fit convention. All lowercase, no plural nouns

### PR DESCRIPTION
**Pull request by recalculated**
Looks cleaner and gets rid of a bunch of warnings in AndroidManifest

### CODE REVIEW

**Comment by Alexendoo** [comment]
Could you undo the line ending changes? Messes with git blame and makes the diff quite unwieldy

**Comment by recalculated** [comment]
Just force pushed a commit without line ending changes

**Comment by l3d00m** [comment]
I really liked this one :(

**Comment by okungnyo** [comment]
What happened? Was it not merged?

**Comment by ccrama** [comment]
It was created right before some major file changes and most of the commit conflicted unfortunately :(. I would be willing to work with @recalculated to get it up again, though!

**Comment by okungnyo** [comment]
That sucks, it looked like a huge commit.

I would be absolutely crushed...

Sorry @recalculated man, I feel for you...

**Comment by recalculated** [comment]
It wasn't really a big deal, just a few refactor > renames. I can rebase on master and resubmit the PR if it's something you guys would want

**Comment by okungnyo** [comment]
@ccrama said he would be willing to work with you to get it up again, no idea why he hasn't replied.

**Pull request closed without merging**
