### PR TITLE
Prevent app from restarting when debug or cAT package is installed

### LINKED ISSUE #1502: Both Slide and Slide (debug) are restarted when pushing a debug build from AS
I actually commented out the lines in the Manifest for the receiver AND commented out the code inside `onReceive()` in `CheckInstall.java` and this is still happening.

### PR DESCRIPTION
**Pull request by Alexendoo**
Fixes #1502

Not sure what the ccrama.me was for, AFAIK that will never be in a packagename unless you have something like me.ccrama.me, so I'll open a PR for it.

Also - what's the purpose of this class?

### CODE REVIEW

**Comment by Nxt3** [comment]
`ccrama.me` is used for the YouTube Video plugin

**Comment by Alexendoo** [comment]
I see... well the package name is incorrect in that case but I'll amend it none the less

**Comment by Nxt3** [comment]
I figured. It's too late now though lol

**Comment by Alexendoo** [comment]
Just before that though, do you know exactly what the class' purpose is @Nxt3? If I'm understanding it correctly whenever you would install pro or the youtube plugin it would start the app? That seems like an antifeature

**Comment by Nxt3** [comment]
No, that's correct; it's supposed to restart to account for the plugin.

Example: You install Pro, but the Pro features won't actually start showing up until you close Slide and reopen it. I can personally attest to that happening. This solves that by restarting Slide for you.

I assume something similar happens with the plugin.

**Comment by ccrama** [comment]
Yes @alexendoo, as it has to restart to enable pro features or enable the YouTube integration

**Pull request closed without merging**
