### PR TITLE
Added Internal GIF View Support for redgifs.com

### PR DESCRIPTION
**Pull request by paulpark03**
Changes made to ContentType.java & GifUtils.java to support Internal GIF view for redgifs.com

### CODE REVIEW

**Comment by paulpark03** [comment]
Some redgifs callback are only accessible via api.redgifs.com callback (some are accessible via both api.gfycat.com & api.redgifs.com). Second commit remaps hostname to redgifs.com.

**Comment by Lokawn** [comment]
This patch is not working for me, it gives "GIF not Found" Error, gifycat is working.

**Comment by ccrama** [comment]
Thank you for the PR! Unfortunately Redgifs has made their API a lot harder to get access to, and I do not want to add support through their official API. I have, instead, added support through Reddit previews here 33a669d1016dcbdc7f22ff88548a32b9a7f8d0fb

**Comment by MetalNeo** [comment]
Slide is no longer recognizing redgifs gifs after updating to 6.6.

**Pull request closed without merging**
