### PR TITLE
Fixed the bottomsheet library version because android studio says so

### PR DESCRIPTION
**Pull request by rosenpin**
Changed to specific version

### CODE REVIEW

**Comment by l3d00m** [comment]
is it ok when i push this in my next commit to github?

**Comment by rosenpin** [comment]
It's ok

**Comment by okungnyo** [comment]
Some info that might help settle you guys' checkbox vs. switch tug-of-war:

https://stackoverflow.com/questions/21231345/when-to-use-checkbox-and-when-switch-android
https://ux.stackexchange.com/questions/63884/checkbox-vs-toggle

Basically, the argument is strong on both sides lol.

**Comment by l3d00m** [comment]
I think we have mostly the on/off situation, so it is better to use switches. Thanks for the links.

**Pull request closed without merging**
