### PR TITLE
Put New Post Notify action in sub sidebar

### PR DESCRIPTION
**Pull request by Nxt3**
- Made the title of the dialog use string formatting
- Put sub in dialog title on newline so it doesn't cutoff weird
- Remove the Be Notified of new Posts from all overflow menus--too crowded

screenshot_20160828-112706

### CODE REVIEW

**Comment by ccrama** [comment]
Looks great! Does it show the user if they've already followed that subrddit for notifications?

**Comment by Nxt3** [comment]
It just does everything it did before when it was in the overflow menu;
just moved the code.

**Comment by Alexendoo** [comment]
Text looks a little long could wrap on smaller phones, go for a simple verb like "notify" perhaps?

**Comment by Nxt3** [comment]
"Subreddit moderators" would have the same issue. "Notify" is too ambiguous. I agree that it's too long though. Just not sure how to shorten it and retain the original meaning.

**Comment by freundTech** [comment]
Just tested it in an emulator. Doesn't wrap with 320x480, mdpi. The drawer is much wider though. (about 90% screen width)

**Comment by Alexendoo** [comment]
"subreddit" could be just dropped from the others as it's implied through context

I think notify would be fine coupled with a checkbox to see if it's on or off, especially since it has an interstitial giving more details

**Comment by Nxt3** [comment]
I'll drop the "Subreddit" text from those actions in another commit. I'll put a checkbox.

**Comment by Nxt3** [comment]
How do I find if the subreddit has this enabled? Can't seem to find a way.

**Comment by Nxt3** [comment]
Oh damn. Did not mean to do that.

**Comment by l3d00m** [comment]
Huh, I does ask you if you sure, doesn't it?

**Comment by Nxt3** [comment]
I pushed to the wrong branch and pushed my commit directly. I'll open a new PR. Already reverted those changes.

**Comment by Nxt3** [comment]
Actually I'm not sure how to handle this. What should I do? My changes on that branch don't count towards changes anymore. :|

**Comment by l3d00m** [comment]
@Alexendoo has the greatest knowledge about git, join the IRC :)

**Pull request merged**
