### PR TITLE
Fixed bad tinting of editor item icons

### LINKED ISSUE #1396: Editing buttons should have less size and more contrast
...I think? Feels like it, especially on a dark background as far as the contrast goes.

### PR DESCRIPTION
**Pull request by Nxt3**
Fixed #1396 

Made the items have more contrast

### CODE REVIEW

**Comment by ccrama** [comment]
Thank you!

**Comment by ccrama** [comment]
Everything is invisible on the white theme, we need a better solution unfortunately :(

**Comment by Nxt3** [comment]
I tried it with the white theme and it was still visible. Could I have a screenshot?

**Comment by ccrama** [comment]
Reply to a post or edit your reply. The background is white and so are the buttons, unfortunately. I think I'll make a parameter on the DoEditorActions class to force White tinting, might be our best bet

**Comment by Alexendoo** [comment]
Wait so what exactly is the colour set to? If it's white where's that coming from when it was set to the main colour of the sub in #1408

**Comment by Nxt3** [comment]
@Alexendoo `?attr/tint` makes it a color that goes well with the base theme. If the base theme is Light, then it makes the icons "dark"; if the base theme is anything else, it makes the icons "lighter". The issue is that in the above screenshot, he has a dark subreddit theme--but the Light base theme--making the icons dark against the dark subreddit theme. We need a way to change it depending on the subreddit theme.

**Pull request merged**
