### PR TITLE
Fixed bug where the toolbar would overlap the content in the overview

### PR DESCRIPTION
**Pull request by rosenpin**
There was an issue with one of the latest commits that caused this bug, here are screenshots of before and after the fix.

Before
After

### CODE REVIEW

**Comment by ccrama** [comment]
Oh sweet, was about to work on this! Thank you! Also, are you on our IRC channel?

**Comment by rosenpin** [comment]
No problem.
And no, I am not.

**Comment by ccrama** [comment]
You should! We hang  out there a lot. The server is snoonet and the channel is #slide if you'd like to join :)

**Comment by rosenpin** [comment]
I will, thanks!

**Pull request merged**
